version: '3'
services:
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    command: npm run start
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
